game:
  config:
    cellSize: 100
    gridSize: 1000
    radius: 50
    showUI: false
    serverHost: wss://ws.memo.bond
server:
  port: 80
datasource:
  url: jdbc:mysql://localhost:3306/game
  username: root
  password: qwer1234
